# yaml for acr build and push 

trigger:
  none

pool:
  vmImasge: ubuntu-latest

stages:
  - stage:
    jobs:
      - job: "package"
        steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'Boardgame/pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false